### ISSUE TITLE
Segments todo's

### ISSUE THREAD

**Issue by galvani** [galvani/mautic#1]
Welcome to the mautic wiki!

# Found 20 TODO items in 9 files
## ContactSegmentFilter.php

- [x] (161, 9) * @TODO remove this, create functions to replace need for this
- [ ] (252, 9) * @TODO replace if not used DateDecorator.php
- [ ] (24, 9) * @TODO @petr please check this method FilterDecoratorInterface.php
- [x] (19, 5) * @TODO @petr document these functions please with phpdoc and meaningful description OperatorOptions.php
- [ ] (71, 17) // @TODO implement in list UI
- [ ] (78, 17) // @TODO implement in list UI

## ContactSegmentQueryBuilder.php

- [ ] (23, 5) * @TODO add exceptions, remove related segments
- [ ] (150, 43) * @param              $whatever     @TODO document this field
- [ ] (236, 9) * @TODO Remove this function
- [ ] (248, 9) * @TODO Remove this function
- [ ] (260, 9) * @TODO Remove this function
- [ ] (272, 9) * @TODO Remove this function

## BaseFilterQueryBuilder.php

- [ ] (101, 24) //@TODO this logic needs to

## DoNotContactFilterQueryBuilder.php

- [ ] (35, 12) //@TODO look at this, the getCrate method is for debuggin only

## ForeignFuncFilterQueryBuilder.php
- [ ] (83, 24) //@TODO this logic needs to

## QueryBuilder.php
- [x] (39, 5) * @TODO rework this to extend the original Query Builder instead of writing new one
- [x] (47, 5) * @TODO extend standing class instead of redefining everything
- [ ] (1414, 9) * @TODO I need to rewrite it, it's no longer necessary like this, we have direct access to query parts
- [ ] (1444, 9) * @TODO I need to rewrite it, it's no longer necessary like this, we have direct access to query parts
- [ ] (1678, 9) * @TODO make this readable and explain
